# Generated by Django 5.2.7 on 2025-10-20 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_description_alter_habit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitrecord',
            name='status',
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='completed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
