# Generated by Django 5.2.7 on 2025-10-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_habitrecord_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='total_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='total_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='HabitRecord',
        ),
    ]
